package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

public class ContactRemoveTests extends TestBase{

    @Test
    public void CanRemoveContact() {
        if (app.contacts().getCount() == 0){
            app.contacts().CreateContact(new ContactData("Irishka", "Mask", "Gdetotam", "+0999923321444", "irishka@mail.com"));
        }
        int countContacts = app.contacts().getCount();
        app.contacts().removeContact();
        int newCountContacts = app.contacts().getCount();
        Assertions.assertEquals(countContacts - 1, newCountContacts);
    }

    @Test
    public void CanRemoveAllContacts(){
        if (app.contacts().getCount() == 0){
            app.contacts().CreateContact(new ContactData("Irishka", "Mask", "Gdetotam", "+0999923321444", "irishka@mail.com"));
        }
        app.contacts().removeAllContacts();
        Assertions.assertEquals(0, app.contacts().getCount());
    }
}

